### ISSUE TITLE
The ability of get shell command output should be enhanced.

### ISSUE THREAD

**Issue by bs111** [openatx/adbutils#1]
if we want to get current Activity,
we can get from by this shell command->dumpsys activity | grep -w ResumedActivity
but ，failed.
>>> print(d.shell_output("dumpsys activity |grep -w ResumedActivity"))
/system/bin/sh: dumpsys activity |grep -w ResumedActivity: not found

example:
>adb shell
W-P311:/ $ dumpsys activity |grep -w ResumedActivity
  ResumedActivity: ActivityRecord{b11e81c u0 com.tencent.mobileqq/.activity.SplashActivity t12623}
W-P311:/ $

**Comment by codeskyblue** [comment]
fix in `0.2.4`
