### ISSUE TITLE
Issue with `device.sync.push` Resulting in `AdbError: FAIL`

### ISSUE THREAD

**Issue by songyuc** [openatx/adbutils#101]
Hello, guys,

I've encountered an issue with `adbutils` while working on a script that involves pushing a file to an Android emulator. The specific method that's causing trouble is `device.sync.push`. Despite successful execution of the same command via `os.system()`, the `device.sync.push` method results in an `AdbError: FAIL` exception.

**Environment:**
- adbutils version: 1.2.15
- Operating System: Windows 10
- Python Version: 3.11.5

**Issue Description:**
The script is intended to clone the `minitouch` repo, build it, and then push the `minitouch` binary to an emulator. The `os.system()` method successfully pushes the file using the `adb push` command. However, when attempting to do the same with `adbutils`, it results in an error.

Here is the relevant part of the script:

```python
# ... [Previous code for context]

print(minitouch_path / "libs" / abi / "minitouch")
os.system(r"adb push D:\Program\xxx\Python_emutouch\minitouch\libs\x86_64\minitouch /data/local/tmp/")
device.sync.push(minitouch_path / "libs" / abi / "minitouch", "/data/local/tmp/", check=True)

# ... [Rest of the code]
```

The error encountered is as follows:

```
adbutils.errors.AdbError: FAIL
```

**Attempts to Resolve:**
- Confirmed that the file path is correct and the file exists.
- Checked the device connection and ensured it is stable.
- Tried simplifying the code to isolate the issue.

I'm unsure why `device.sync.push` is failing while `os.system()` succeeds. Any insights or suggestions would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Yucheng Song

**Comment by codeskyblue** [comment]
Change the destination to /data/local/tmp/minitouch

**Comment by shidalao** [comment]
change your dst directory to a specific file name, such as "/data/local/tmp/" to "/data/local/tmp/123.txt"
