### ISSUE TITLE
Feature Request: Add `restart_adb_server()` Function to Simplify ADB Server Restart

### ISSUE THREAD

**Issue by songyuc** [openatx/adbutils#102]
### Feature Description
I would like to propose the addition of a new function, `restart_adb_server()`, to the `adbutils` library. This function would encapsulate the functionality to restart the Android Debug Bridge (ADB) server, making it more convenient for developers to perform this common task.

### Rationale
Currently, restarting the ADB server requires calling two separate functions: `kill_server()` and `start_server()`. While this is effective, it can be more streamlined. Implementing a `restart_adb_server()` function would simplify the code needed to restart the ADB server, making the process more efficient and user-friendly.

### Proposed Implementation
The `restart_adb_server()` function could internally call the existing `kill_server()` and `start_server()` functions. This would encapsulate the restart logic within a single, easy-to-use function. Here's a rough implementation idea:

```python
def restart_adb_server():
    kill_server()
    start_server()
```

### Potential Benefits
- **Simplicity**: Provides a straightforward way to restart the ADB server.
- **Convenience**: Saves time for developers who frequently restart the ADB server during development.
- **Code Cleanliness**: Reduces the need for repetitive code in projects that use `adbutils`.

### Conclusion
I believe that adding this function would be a valuable enhancement to the `adbutils` library, making it more convenient for developers working with Android devices. I look forward to hearing your thoughts on this suggestion. Thank you for considering this feature request.

Best regards,
Yucheng Song

**Comment by codeskyblue** [comment]
可以啊，提个pr呗

**Comment by songyuc** [comment]
尊敬的@codeskyblue,

我考虑将这个函数放在代码库中`adb.device()`函数之前。请问，您认为这样的安排是否符合库的结构和设计理念？
对于在`adbutils`库中放置这个函数的最佳位置，非常欢迎任何反馈或建议。

感谢您的时间和支持。

**Comment by codeskyblue** [comment]
Lgtm

**Comment by songyuc** [comment]
您好，
函数的实现如下：
```python
def restart_adb_server():
    try:
        # 停止ADB服务
        subprocess.run(["adb", "kill-server"], check=True)
        # 启动ADB服务
        subprocess.run(["adb", "start-server"], check=True)

    except subprocess.CalledProcessError as e:
        print(f"执行ADB命令时出错：{e}")
```
您看，这样的实现可以吗

**Comment by codeskyblue** [comment]
不要用subprocess

**Comment by codeskyblue** [comment]
这尼玛，GPT机器人吗？

**Comment by songyuc** [comment]
老师，您好，我不是机器人，我是华科的一名学生哈

**Comment by LiJiaHeer** [comment]
哈哈哈哈哈哈笑死了 谢谢Yucheng Song

**Comment by codeskyblue** [comment]
直接提pr好了，不要一直留言了
