### ISSUE TITLE
ADB 录制屏幕失败

### ISSUE THREAD

**Issue by Maoz333** [openatx/adbutils#103]
当使用adb录屏时，会报
ERROR: unable to configure video/avc codec at 1920x1080 (err=-22)
WARNING: failed at 1920x1080, retrying at 1280x720
ERROR: unable to configure video/avc codec at 1280x720 (err=-22)
这个错误，然后生产的文件只有0kb

**Comment by codeskyblue** [comment]
试试直接用screenrecord 行不行

**Comment by Maoz333** [comment]
> 尝试直接用screenrecord行不行

直接调用screenrecord也不行，目前还没找到原因🥲

**Comment by codeskyblue** [comment]
adb如果不行的话，也可以试试 scrcpy来录屏
