### ISSUE TITLE
Package is missing py.typed

### ISSUE THREAD

**Issue by gregersn** [openatx/adbutils#122]
Information about packaging with py.typed
https://peps.python.org/pep-0561/

**Comment by codeskyblue** [comment]
I don't understand

**Comment by gregersn** [comment]
From the documentation for PEP 561

> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing. 

The file is missing from this package. Some Python tooling relies on this file to understand that a library has types, and will report that types are missing if the marker is not there. 

When installed, in the `site-packages/adbutils` folder there should be an empty file called `py.typed`.

https://safjan.com/the-importance-of-adding-py-typed-file-to-your-typed-package/

https://peps.python.org/pep-0561/#packaging-type-information

**Comment by gregersn** [comment]
Something like this: https://github.com/openatx/adbutils/pull/123

**Comment by codeskyblue** [comment]
merged
