### ISSUE TITLE
windows平台adb服务未启动时会报错，不能自动启动

### ISSUE THREAD

**Issue by Zeros2619** [openatx/adbutils#128]
![image](https://github.com/openatx/adbutils/assets/35124806/16888723-299e-4c44-af5f-6456d3aafb7e)
是不是应该将windows平台的AdbTimeout异常也做捕获， 以启动adb服务。

**Comment by codeskyblue** [comment]
related https://github.com/openatx/adbutils/pull/127#event-12943311648
