### ISSUE TITLE
d.app_stop(package_name)提示TypeError: _run() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by congyingHHZ** [openatx/adbutils#15]
`    def app_stop(self, package_name: str):
        """ stop app with "am force-stop"
        """
        self._run('am', 'force-stop', package_name)`

这里调的self._run()传入应该是个列表吧，改为self._run(['am', 'force-stop', package_name])运行正常

**Comment by codeskyblue** [comment]
好的，我看下

**Comment by codeskyblue** [comment]
fixed in 0.6.3
