### ISSUE TITLE
Screenrecord not stopping

### ISSUE THREAD

**Issue by eyeojeff** [openatx/adbutils#28]
For some reason it seems that the `stop()` method on the `ScreenRecord` class does not work. After sending a `stop_and_pull` call the function hangs until the 3 min timeout on the `read_until_close` step.

To reproduce:

```
import time
from adbutils import adb

device = adb.device()
recording = device.screenrecord(remote_path="/data/local/tmp/foo.mp4") 
time.sleep(5)
recording.stop_and_pull("foo.mp4")
```

This should take around 5 seconds to run, but takes a little over 3 minutes

**Comment by codeskyblue** [comment]
Looks like this method is not very stable
