### ISSUE TITLE
Screenrecord Error

### ISSUE THREAD

**Issue by Nucito** [openatx/adbutils#46]
```
import time
from adbutils import adb

d = adb.device()

rec = d.screenrecord(remote_path="/data/local/tmp/cu.mp4")
time.sleep(5)
rec.stop_and_pull("fc.mp4")
```

The result:

**AttributeError: '_AdbStreamConnection' object has no attribute 'send'**

**Comment by JustinDBruce** [comment]
Any updates here?

**Comment by codeskyblue** [comment]
fixed

**Comment by MilkFlavor** [comment]
Wait it still exists?

**Comment by MilkFlavor** [comment]
`from adbutils import AdbDevice, AdbError, Network, _AdbStreamConnection, adb`
`ImportError: cannot import name '_AdbStreamConnection' from 'adbutils' (/home/poka/.local/lib/python3.8/site-packages/adbutils/__init__.py)`

**Comment by codeskyblue** [comment]
_AdbStreamConnection class is removed, use AdbConnection instead.
