### ISSUE TITLE
adb.device_list()获取不到serial，使用os.popen('adb shell').read()可以获取到serial

### ISSUE THREAD

**Issue by fromzhou** [openatx/adbutils#61]
您好！
请问，使用adb.device_list()获取不到serial
反而使用os.popen("adb devices").read()，可以获取，这是什么原因导致的呢
![image](https://user-images.githubusercontent.com/88641723/163346909-06dd43cc-3b2c-4e17-a995-31a6e3be8733.png)

**Comment by abeelan** [comment]
找一个在线设备试试呢？ adb.devices_list() 有可能过滤了 offline 状态的设备。

**Comment by codeskyblue** [comment]
@abeelan 是的offline的被过滤掉了

**Comment by codeskyblue** [comment]
Use method list will see offline device
```
import adbutils

adb = adbutils.AdbClient(host="127.0.0.1", port=5037)
for info in adb.list():
    print(info.serial, info.state)
    # <serial> <device|offline>
```
