### ISSUE TITLE
adb.sync.push(src,dst)不生效

### ISSUE THREAD

**Issue by leo19850812** [openatx/adbutils#62]
我的命令如下：
adb_device = adbutils.AdbClient(host=params.adbIP, port=params.adbPort).device()
adb_device.sync.push('本地的二进制文件', '设备的路径文件')

问题：
失败原因不知道

如果我推送，这样子貌似可以
adb_device.sync.push(b'本地的二进制文件内容', '设备的路径文件')

**Comment by codeskyblue** [comment]
我试了下，dst是目录的话，确实会出问题。但是如果写成目标路径的话。看起来是正常的

```
d.sync.push("a.jpg", "/sdcard/a.jpg")
```

**Comment by codeskyblue** [comment]
已完成
