### ISSUE TITLE
adbutil 0.16.0 screenrecord录屏有问题

### ISSUE THREAD

**Issue by xdfsa** [openatx/adbutils#65]
######## 看了一下源码，是push的脚本名称和运行的脚本名称不一致导致的，希望能修改一下

![screenshot_3](https://user-images.githubusercontent.com/43033679/167853774-1ad200b6-2166-4856-a17c-8acd28b2d89f.png)

######## 另外还有个问题，对于手机内没有内置screenrecord如何实现录屏呢（比如华为手机和某些android机型），能用提供minicap录屏的通用接口呢？

**Comment by codeskyblue** [comment]
haha. my mistake.

**Comment by codeskyblue** [comment]
fixed in 0.16.2
