### ISSUE TITLE
Add support for emu command

### ISSUE THREAD

**Issue by leinardi** [openatx/adbutils#66]
I would like to be able to send sensor data to the emulator. From command line I can use something like this to simulate, for example, a 1 second device shake:

```
adb emu sensor set acceleration 100:100:100; sleep 1; adb emu sensor set acceleration 0:0:0
```

It would be nice to be able to use `adbutils` to send this `emu` commands.

**Comment by codeskyblue** [comment]
pr welcome. my computer will stuck when run emulator

**Comment by leinardi** [comment]
I just notice that this is actually doable using `adb_output()`:

```python
device.adb_output(['emu', 'sensor', 'set', 'acceleration', '100:100:100'])
time.sleep(1)
device.adb_output(['emu', 'sensor', 'set', 'acceleration', '0:0:0'])
```
