### ISSUE TITLE
'AdbConnection' isn't found in adbutils?

### ISSUE THREAD

**Issue by MilkFlavor** [openatx/adbutils#67]
So according to https://github.com/openatx/adbutils/issues/46#issuecomment-1127167371 '_AdbStreamConnection' was removed from 'adbutils'. However, when removing and replacing with 'AdbConnection'.

Error Message:
``Traceback (most recent call last):
  File "src/main.py", line 1, in <module>
    import scrcpy
  File "/mnt/c/Users/shiba/OneDrive/Documents/Mirror/src/scrcpy/__init__.py", line 6, in <module>
    from .core import Client
  File "/mnt/c/Users/shiba/OneDrive/Documents/Mirror/src/scrcpy/core.py", line 11, in <module>
    from adbutils import AdbDevice, AdbError, Network, AdbConnection, adb
ImportError: cannot import name 'AdbConnection' from 'adbutils' (/home/poka/.local/lib/python3.8/site-packages/adbutils/__init__.py)``

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/169224602-f73a3973-ee9b-4139-9390-8c94aaca023c.png)

**Comment by MilkFlavor** [comment]
Yup, that was something on my part.
