### ISSUE TITLE
Fix README.md change devices() -> device_list()

### ISSUE THREAD

**Issue by ScriptHound** [openatx/adbutils#70]
README.md tells me that to list all the devices connected i have to adb.devices(). 
But this raises an erorr:
```
adb.devices()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 adb.devices()

AttributeError: 'AdbClient' object has no attribute 'devices'
```

I've tried help(adb) and found device_list method, which listed all the devices connected.
So, I suggest updating README.md https://github.com/openatx/adbutils#list-all-the-devices-and-get-device-object

**Comment by stavis-dev** [comment]
I got with the same problem. Made a pull request. Waiting for acceptance.
[ pull request](https://github.com/openatx/adbutils/pull/69)
