### ISSUE TITLE
binaries path is blank on ubuntu18

### ISSUE THREAD

**Issue by yinkh** [openatx/adbutils#74]
![image](https://user-images.githubusercontent.com/8170059/180937678-2f53b30f-a1ee-42bd-ae80-1394f11c3354.png)
![image](https://user-images.githubusercontent.com/8170059/180937504-d2ac61ce-f516-4ca7-9761-8f5410fba979.png)

python version is 3.9.13
system is Ubuntu 18.04.5 LTS

only README.md inside `python3.9/site-packages/adbutils/binaries`

**Comment by codeskyblue** [comment]
Try 1.0.4, just updated build_wheel.py

**Comment by yinkh** [comment]
![image](https://user-images.githubusercontent.com/8170059/181001717-2c426fa5-6fec-4c45-9267-d909737fb364.png)
fixed!
