### ISSUE TITLE
Python3.10版本collections包报错

### ISSUE THREAD

**Issue by BluesRem** [openatx/adbutils#92]
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by BadPlayer555** [comment]
Try to update the package: requests by conda/pip

**Comment by Antoniosant** [comment]
Hi! 
i've tried to update requets package but i get that: 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
adbutils 1.2.11 requires requests<2.16, but you have requests 2.31.0 which is incompatible.

Any other idea?

**Comment by nhonhoem0166** [comment]
> Hi! i've tried to update requets package but i get that:
> 
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. adbutils 1.2.11 requires requests<2.16, but you have requests 2.31.0 which is incompatible.
> 
> Any other idea?
up to requests 2.31.0
pip install requests -U
it work for me
![image](https://github.com/openatx/adbutils/assets/56016610/86666155-f9f9-418a-aef3-e2b965c5b397)
