### ISSUE TITLE
adbutils 1.2.11 has an incorrect `python_requires` spec

### ISSUE THREAD

**Issue by mhils** [openatx/adbutils#94]
It looks like adbutils 1.2.11 was released to provide support for Python 3.6.x. However, the [commit to limit the version](https://github.com/openatx/adbutils/commit/fb73aa68eca5a1be57c1a3ef8d5eed0c322073d3) contains a bug: Instead of `'~=3.6'`, the python version should be `'~=3.6.0'`. `~=3.6` means `>=3.6,<4`, `~=3.6.0` means `>=3.6.0,<3.7`. This currently breaks `pip install adbutils` on Python 3.7 and above (https://github.com/openatx/adbutils/issues/92).

**Comment by codeskyblue** [comment]
I'm try to fix it now. The lastest version is 2.2.3, which limit the python version >= 3.8
