### ISSUE TITLE
MultiScreen Support

### ISSUE THREAD

**Issue by daniaddam** [openatx/adbutils#98]
Hey Folks,

I found out, adbutils doesn't support device with MultiScreens (e.g. foldable phones). I modified locally the package. If you add me as contributor, I would like to submit my changes.

Cheers
Dani

**Comment by codeskyblue** [comment]
pull request is welcome. If you got many pull requests, you will be added to maintainers.

**Comment by codeskyblue** [comment]
click, screenshot now support display_id
